const TattooStyles = [
    { name: 'Any' },
    { name: 'Black & Gray' },
    { name: 'Blackwork' },
    { name: 'Chicano' },
    { name: 'Dotwork' },
    { name: 'Fineline' },
    { name: 'Geometric' },
    { name: 'Poked' },
    { name: 'Dark Art' },
    { name: 'Japanese (Irezumi)' },
    { name: 'Lettering' },
    { name: 'Neo Traditional' },
    { name: 'School' },
    { name: 'Ornamental' },
    { name: 'Realism' },
    { name: 'Illustrative' },
    { name: 'Old School (Traditional)' },
    { name: 'Polka Style' },
    { name: 'Tribal' },
    { name: 'Watercolor' },
    { name: 'Surrealism' },
    { name: 'Cosmetic' },
    { name: 'Ignorant' },
];

module.exports = TattooStyles;