export const GET_ARTIST_PROFILE = 'GET_ARTIST_PROFILE';
export const SAVE_ARTIST_PROFILE = 'SAVE_ARTIST_PROFILE';
export const ARTIST_PROFILE_ERROR = 'ARTIST_PROFILE_ERROR';
export const SET_ALERT = 'SET_ALERT';
export const REMOVE_ALERT = 'REMOVE_ALERT';

export const GET_TATTOO_STYLES = 'GET_TATTOO_STYLES';
export const TATTOO_STYLES_ERROR =  'TATTOO_STYLES_ERROR';