export const SET_ALERT = 'SET_ALERT';
export const REMOVE_ALERT = 'REMOVE_ALERT';

export const FETCH_ARTISTS = 'FETCH_ARTISTS';
export const FETCH_ARTISTS_ERROR = 'FETCH_ARTISTS_ERROR';
export const GET_ARTIST_PROFILE = 'GET_ARTIST_PROFILE';
export const SAVE_ARTIST_PROFILE = 'SAVE_ARTIST_PROFILE';
export const ARTIST_PROFILE_ERROR = 'ARTIST_PROFILE_ERROR';
export const RESET_ARTISTS = 'RESET_ARTISTS';

export const FETCH_TATTOO_STYLES_SUCCESS = 'FETCH_TATTOO_STYLES_SUCCESS';
export const FETCH_TATTOO_STYLES_FAIL =  'FETCH_TATTOO_STYLES_FAIL';

export const SAVE_USER_SUCCESS = 'SAVE_USER_SUCCESS';
export const SAVE_USER_FAIL = 'SAVE_USER_FAIL';
export const SAVE_PICTURE_SUCCESS = 'SAVE_PICTURE_SUCCESS';
export const SAVE_PICTURE_FAIL = 'SAVE_PICTURE_FAIL';
export const SIGNIN_SUCCESS = 'SIGNIN_SUCCESS';
export const SIGNIN_FAIL = 'SIGNIN_FAIL';
export const FETCH_USER_INFO = 'FETCH_USER_INFO';
export const FETCH_USER_PICTURE = 'FETCH_USER_PICTURE';

export const FETCH_STUDIOS = 'FETCH_STUDIOS';
export const FETCH_STUDIO = 'FETCH_STUDIO';
export const SAVE_STUDIO_SUCCESS = 'SAVE_STUDIO_SUCCESS';
export const SAVE_STUDIO_FAIL = 'SAVE_STUDIO_FAIL';

export const RESET_PASSWORD_EMAIL_SUCCESS = 'RESET_PASSWORD_EMAIL_SUCCESS';
export const RESET_PASSWORD_EMAIL_FAIL = 'RESET_PASSWORD_EMAIL_FAIL';
export const RESET_PASSWORD_SUCCESS = 'RESET_PASSWORD_SUCCESS';
export const RESET_PASSWORD_FAIL = 'RESET_PASSWORD_FAIL';