export const SET_ALERT = 'SET_ALERT';
export const REMOVE_ALERT = 'REMOVE_ALERT';

export const LOADING = 'LOADING';

export const FETCH_ARTISTS = 'FETCH_ARTISTS';
export const FETCH_ARTIST = 'FETCH_ARTIST';
export const FETCH_ARTIST_PROFILE = 'FETCH_ARTIST_PROFILE';
export const SAVE_ARTIST_PROFILE = 'SAVE_ARTIST_PROFILE';
export const SAVE_ARTIST_IMAGE = 'SAVE_ARTIST_IMAGE';
export const SAVE_ARTIST_COVER = 'SAVE_ARTIST_COVER';
export const SAVE_ARTIST_PORTFOLIO = 'SAVE_ARTIST_PORTFOLIO';
export const DELETE_ARTIST = 'DELETE_ARTIST';
export const ARTIST_ERROR = 'ARTIST_ERROR';

export const FETCH_TATTOO_STYLES_SUCCESS = 'FETCH_TATTOO_STYLES_SUCCESS';
export const FETCH_TATTOO_STYLES_FAIL = 'FETCH_TATTOO_STYLES_FAIL';

export const FETCH_USER_INFO = 'FETCH_USER_INFO';
export const FETCH_USER_PICTURE = 'FETCH_USER_PICTURE';
export const SAVE_USER_SUCCESS = 'SAVE_USER_SUCCESS';
export const SAVE_USER_FAIL = 'SAVE_USER_FAIL';
export const SAVE_PICTURE_SUCCESS = 'SAVE_PICTURE_SUCCESS';
export const SIGNIN_SUCCESS = 'SIGNIN_SUCCESS';
export const SIGNIN_FAIL = 'SIGNIN_FAIL';
export const USER_DELETED = 'USER_DELETED';
export const USER_ERROR = 'USER_ERROR';

export const FETCH_STUDIOS = 'FETCH_STUDIOS';
export const FETCH_STUDIO = 'FETCH_STUDIO';
export const FETCH_STUDIO_PROFILE = 'FETCH_STUDIO_PROFILE';
export const SAVE_STUDIO_SUCCESS = 'SAVE_STUDIO_SUCCESS';
export const SAVE_LOGO_SUCCESS = 'SAVE_LOGO_SUCCESS';
export const SAVE_COVER_SUCCESS = 'SAVE_COVER_SUCCESS';
export const SAVE_PHOTOS_SUCCESS = 'SAVE_PHOTOS_SUCCESS';
export const DELETE_STUDIO = 'DELETE_STUDIO';
export const STUDIO_ERROR = 'STUDIO_ERROR';

export const RESET_PASSWORD_EMAIL_SUCCESS = 'RESET_PASSWORD_EMAIL_SUCCESS';
export const RESET_PASSWORD_EMAIL_FAIL = 'RESET_PASSWORD_EMAIL_FAIL';
export const RESET_PASSWORD_SUCCESS = 'RESET_PASSWORD_SUCCESS';
export const RESET_PASSWORD_FAIL = 'RESET_PASSWORD_FAIL';
